// Hand-added instance for the q2_0 KV cache, not generated by generate_cu_files.py.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q2_0, GGML_TYPE_Q2_0);
